/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../google/api/annotations_pb.js');
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.exportSymbol('proto.dt.apigw.v1.DismissNotificationRequest', null, global);
goog.exportSymbol('proto.dt.apigw.v1.GetNotificationRequest', null, global);
goog.exportSymbol('proto.dt.apigw.v1.ListNotificationsRequest', null, global);
goog.exportSymbol('proto.dt.apigw.v1.ListNotificationsResponse', null, global);
goog.exportSymbol('proto.dt.apigw.v1.Notification', null, global);
goog.exportSymbol('proto.dt.apigw.v1.NotificationSeverityLevel', null, global);
goog.exportSymbol('proto.dt.apigw.v1.NotificationStatus', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dt.apigw.v1.ListNotificationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dt.apigw.v1.ListNotificationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dt.apigw.v1.ListNotificationsRequest.displayName = 'proto.dt.apigw.v1.ListNotificationsRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dt.apigw.v1.ListNotificationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dt.apigw.v1.ListNotificationsRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dt.apigw.v1.ListNotificationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    objectId: msg.getObjectId(),
    level: msg.getLevel(),
    status: msg.getStatus(),
    pageSize: msg.getPageSize(),
    pageToken: msg.getPageToken(),
    ignoreTtl: msg.getIgnoreTtl()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dt.apigw.v1.ListNotificationsRequest}
 */
proto.dt.apigw.v1.ListNotificationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dt.apigw.v1.ListNotificationsRequest;
  return proto.dt.apigw.v1.ListNotificationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dt.apigw.v1.ListNotificationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dt.apigw.v1.ListNotificationsRequest}
 */
proto.dt.apigw.v1.ListNotificationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectId(value);
      break;
    case 2:
      var value = /** @type {!proto.dt.apigw.v1.NotificationSeverityLevel} */ (reader.readEnum());
      msg.setLevel(value);
      break;
    case 3:
      var value = /** @type {!proto.dt.apigw.v1.NotificationStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIgnoreTtl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dt.apigw.v1.ListNotificationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.ListNotificationsRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getObjectId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = this.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = this.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = this.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getIgnoreTtl();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dt.apigw.v1.ListNotificationsRequest} The clone.
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.dt.apigw.v1.ListNotificationsRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string object_id = 1;
 * @return {string}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getObjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setObjectId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional NotificationSeverityLevel level = 2;
 * @return {!proto.dt.apigw.v1.NotificationSeverityLevel}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getLevel = function() {
  return /** @type {!proto.dt.apigw.v1.NotificationSeverityLevel} */ (jspb.Message.getFieldProto3(this, 2, 0));
};


/** @param {!proto.dt.apigw.v1.NotificationSeverityLevel} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setLevel = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional NotificationStatus status = 3;
 * @return {!proto.dt.apigw.v1.NotificationStatus}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getStatus = function() {
  return /** @type {!proto.dt.apigw.v1.NotificationStatus} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {!proto.dt.apigw.v1.NotificationStatus} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional int32 page_size = 4;
 * @return {number}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 4, 0));
};


/** @param {number} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setPageSize = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string page_token = 5;
 * @return {string}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setPageToken = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional bool ignore_ttl = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.getIgnoreTtl = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldProto3(this, 6, false));
};


/** @param {boolean} value  */
proto.dt.apigw.v1.ListNotificationsRequest.prototype.setIgnoreTtl = function(value) {
  jspb.Message.setField(this, 6, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dt.apigw.v1.ListNotificationsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.dt.apigw.v1.ListNotificationsResponse.repeatedFields_, null);
};
goog.inherits(proto.dt.apigw.v1.ListNotificationsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dt.apigw.v1.ListNotificationsResponse.displayName = 'proto.dt.apigw.v1.ListNotificationsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.dt.apigw.v1.ListNotificationsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dt.apigw.v1.ListNotificationsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dt.apigw.v1.ListNotificationsResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dt.apigw.v1.ListNotificationsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    notificationsList: jspb.Message.toObjectList(msg.getNotificationsList(),
    proto.dt.apigw.v1.Notification.toObject, includeInstance),
    nextPageToken: msg.getNextPageToken()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dt.apigw.v1.ListNotificationsResponse}
 */
proto.dt.apigw.v1.ListNotificationsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dt.apigw.v1.ListNotificationsResponse;
  return proto.dt.apigw.v1.ListNotificationsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dt.apigw.v1.ListNotificationsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dt.apigw.v1.ListNotificationsResponse}
 */
proto.dt.apigw.v1.ListNotificationsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.dt.apigw.v1.Notification;
      reader.readMessage(value,proto.dt.apigw.v1.Notification.deserializeBinaryFromReader);
      msg.getNotificationsList().push(value);
      msg.setNotificationsList(msg.getNotificationsList());
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dt.apigw.v1.ListNotificationsResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.ListNotificationsResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNotificationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.dt.apigw.v1.Notification.serializeBinaryToWriter
    );
  }
  f = this.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dt.apigw.v1.ListNotificationsResponse} The clone.
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.cloneMessage = function() {
  return /** @type {!proto.dt.apigw.v1.ListNotificationsResponse} */ (jspb.Message.cloneMessage(this));
};


/**
 * repeated Notification notifications = 1;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.dt.apigw.v1.Notification>}
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.getNotificationsList = function() {
  return /** @type{!Array.<!proto.dt.apigw.v1.Notification>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.dt.apigw.v1.Notification, 1));
};


/** @param {Array.<!proto.dt.apigw.v1.Notification>} value  */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.setNotificationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


proto.dt.apigw.v1.ListNotificationsResponse.prototype.clearNotificationsList = function() {
  this.setNotificationsList([]);
};


/**
 * optional string next_page_token = 2;
 * @return {string}
 */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.ListNotificationsResponse.prototype.setNextPageToken = function(value) {
  jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dt.apigw.v1.GetNotificationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dt.apigw.v1.GetNotificationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dt.apigw.v1.GetNotificationRequest.displayName = 'proto.dt.apigw.v1.GetNotificationRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dt.apigw.v1.GetNotificationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dt.apigw.v1.GetNotificationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dt.apigw.v1.GetNotificationRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dt.apigw.v1.GetNotificationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    notificationId: msg.getNotificationId()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dt.apigw.v1.GetNotificationRequest}
 */
proto.dt.apigw.v1.GetNotificationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dt.apigw.v1.GetNotificationRequest;
  return proto.dt.apigw.v1.GetNotificationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dt.apigw.v1.GetNotificationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dt.apigw.v1.GetNotificationRequest}
 */
proto.dt.apigw.v1.GetNotificationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dt.apigw.v1.GetNotificationRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.GetNotificationRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dt.apigw.v1.GetNotificationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.GetNotificationRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNotificationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dt.apigw.v1.GetNotificationRequest} The clone.
 */
proto.dt.apigw.v1.GetNotificationRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.dt.apigw.v1.GetNotificationRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string notification_id = 1;
 * @return {string}
 */
proto.dt.apigw.v1.GetNotificationRequest.prototype.getNotificationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.GetNotificationRequest.prototype.setNotificationId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dt.apigw.v1.DismissNotificationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dt.apigw.v1.DismissNotificationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dt.apigw.v1.DismissNotificationRequest.displayName = 'proto.dt.apigw.v1.DismissNotificationRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dt.apigw.v1.DismissNotificationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dt.apigw.v1.DismissNotificationRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dt.apigw.v1.DismissNotificationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    notificationId: msg.getNotificationId()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dt.apigw.v1.DismissNotificationRequest}
 */
proto.dt.apigw.v1.DismissNotificationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dt.apigw.v1.DismissNotificationRequest;
  return proto.dt.apigw.v1.DismissNotificationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dt.apigw.v1.DismissNotificationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dt.apigw.v1.DismissNotificationRequest}
 */
proto.dt.apigw.v1.DismissNotificationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNotificationId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dt.apigw.v1.DismissNotificationRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.DismissNotificationRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getNotificationId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dt.apigw.v1.DismissNotificationRequest} The clone.
 */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.dt.apigw.v1.DismissNotificationRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string notification_id = 1;
 * @return {string}
 */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.getNotificationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.DismissNotificationRequest.prototype.setNotificationId = function(value) {
  jspb.Message.setField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dt.apigw.v1.Notification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dt.apigw.v1.Notification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dt.apigw.v1.Notification.displayName = 'proto.dt.apigw.v1.Notification';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dt.apigw.v1.Notification.prototype.toObject = function(opt_includeInstance) {
  return proto.dt.apigw.v1.Notification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dt.apigw.v1.Notification} msg The msg instance to transform.
 * @return {!Object}
 */
proto.dt.apigw.v1.Notification.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    objectId: msg.getObjectId(),
    subject: msg.getSubject(),
    message: msg.getMessage(),
    level: msg.getLevel(),
    status: msg.getStatus(),
    created: (f = msg.getCreated()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    ttl: (f = msg.getTtl()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dt.apigw.v1.Notification}
 */
proto.dt.apigw.v1.Notification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dt.apigw.v1.Notification;
  return proto.dt.apigw.v1.Notification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dt.apigw.v1.Notification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dt.apigw.v1.Notification}
 */
proto.dt.apigw.v1.Notification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 5:
      var value = /** @type {!proto.dt.apigw.v1.NotificationSeverityLevel} */ (reader.readEnum());
      msg.setLevel(value);
      break;
    case 6:
      var value = /** @type {!proto.dt.apigw.v1.NotificationStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 8:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setTtl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.dt.apigw.v1.Notification} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.Notification.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dt.apigw.v1.Notification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.dt.apigw.v1.Notification.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getObjectId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getSubject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = this.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = this.getCreated();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = this.getTtl();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.dt.apigw.v1.Notification} The clone.
 */
proto.dt.apigw.v1.Notification.prototype.cloneMessage = function() {
  return /** @type {!proto.dt.apigw.v1.Notification} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.dt.apigw.v1.Notification.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.Notification.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string object_id = 2;
 * @return {string}
 */
proto.dt.apigw.v1.Notification.prototype.getObjectId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.Notification.prototype.setObjectId = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string subject = 3;
 * @return {string}
 */
proto.dt.apigw.v1.Notification.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.Notification.prototype.setSubject = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string message = 4;
 * @return {string}
 */
proto.dt.apigw.v1.Notification.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.dt.apigw.v1.Notification.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional NotificationSeverityLevel level = 5;
 * @return {!proto.dt.apigw.v1.NotificationSeverityLevel}
 */
proto.dt.apigw.v1.Notification.prototype.getLevel = function() {
  return /** @type {!proto.dt.apigw.v1.NotificationSeverityLevel} */ (jspb.Message.getFieldProto3(this, 5, 0));
};


/** @param {!proto.dt.apigw.v1.NotificationSeverityLevel} value  */
proto.dt.apigw.v1.Notification.prototype.setLevel = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional NotificationStatus status = 6;
 * @return {!proto.dt.apigw.v1.NotificationStatus}
 */
proto.dt.apigw.v1.Notification.prototype.getStatus = function() {
  return /** @type {!proto.dt.apigw.v1.NotificationStatus} */ (jspb.Message.getFieldProto3(this, 6, 0));
};


/** @param {!proto.dt.apigw.v1.NotificationStatus} value  */
proto.dt.apigw.v1.Notification.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp created = 7;
 * @return {proto.google.protobuf.Timestamp}
 */
proto.dt.apigw.v1.Notification.prototype.getCreated = function() {
  return /** @type{proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/** @param {proto.google.protobuf.Timestamp|undefined} value  */
proto.dt.apigw.v1.Notification.prototype.setCreated = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.dt.apigw.v1.Notification.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dt.apigw.v1.Notification.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Duration ttl = 8;
 * @return {proto.google.protobuf.Duration}
 */
proto.dt.apigw.v1.Notification.prototype.getTtl = function() {
  return /** @type{proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 8));
};


/** @param {proto.google.protobuf.Duration|undefined} value  */
proto.dt.apigw.v1.Notification.prototype.setTtl = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


proto.dt.apigw.v1.Notification.prototype.clearTtl = function() {
  this.setTtl(undefined);
};


/**
 * Returns whether this field is set.
 * @return{!boolean}
 */
proto.dt.apigw.v1.Notification.prototype.hasTtl = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * @enum {number}
 */
proto.dt.apigw.v1.NotificationSeverityLevel = {
  INFO: 0,
  WARNING: 1,
  ALERT: 2
};

/**
 * @enum {number}
 */
proto.dt.apigw.v1.NotificationStatus = {
  ANY: 0,
  ACTIVE: 1,
  CLEARED: 2,
  DISMISSED: 3
};

goog.object.extend(exports, proto.dt.apigw.v1);
